Ensure that tunneled payloads are parsed
FlowFuse/device-agent pull request #189
Opened 2023-10-25 21:00 UTC by hardillb

## Description

HTTP Body is JSON.stringify() before being sent down the tunnel need to JSON.parse() before forwarding on to editor

## Related Issue(s)

flowfuse/flowfuse#2999

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

2023-10-26 08:13 UTC, hardillb commented
For reference here is the other end of the tunnel `JSON.stringify()` call

2023-10-26 08:59 UTC, knolleary commented
With this change, I can load the device editor, but I cannot deploy any changes

2023-11-01 06:50 UTC, hardillb commented
When you get a second can you look at this revised fix, shouldn't break anything this time and still allow UIBuilder to work.

2023-11-01 13:44 UTC, hardillb commented
@Steve-Mcl If you get a moment can you kick the tires on this please. I've given it a better test than the first version and I'm 99% sure it won't break anything this time.

2023-11-06 11:06 UTC, knolleary requested changes

2023-11-06 11:06 UTC, knolleary commented on lib/editor/tunnel.js
> +                    }
```suggestion
                    // debug(`body ${request.body}`)
                    let body = request.body
                    if (body && body[0] === '"') {
                        try {
                            body = JSON.parse(body)
                        } catch (err) {
                            // ignore
                        }
                    }
```

This feels an expensive way to only parse strings. Suggest adding a check to see if it looks like a JSON encoded String before attempting the parse.

2023-11-06 13:20 UTC, knolleary approved these changes

2023-11-06 13:20 UTC, merged